10_Sprint_Filmorate_start_v1
Svetlanarozanova1983/java-filmorate pull request #3
Opened 2024-09-05 21:03 UTC by Svetlanarozanova1983

2024-09-06 08:33 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        try {
Нужно стремится к единообразию при обработке ошибок. В методе create ты перехватываешь эксепшен, чтобы его залогировать. Вполне допустимо. Но в методе update при практически идентичных обстоятельствах этого не сделано?
А лучше всего логгирование ошибки встроить в метод  validateUser, т.к. в данном случае он основной источник эксепшенов. И тогда в методах контроллера не нужно будет использовать try-catch для логгирования ошибки. Меньше кода - легче читать и сопровождать)

2024-09-06 08:42 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (users.containsKey(input.getId())) {
Есть практика написания кода, которая называется ранний выход (early return).
Смысл в том, чтобы проверить условия для успешного выполнения метода в самом начале и выйти при неуспехе (или выбросить эксепшен). Тем самым в основной части метода будет меньше отступов и код будет легче восприниматься.
```
    @PutMapping()
    public User update(@RequestBody User input) {
        validateUser(input);
        if (!users.containsKey(input.getId())) {
                throw new NotFoundException("Пользователь с id = " + input.getId() + " не найден");
        }
        
        User oldUser = users.get(input.getId());
        oldUser.setEmail(input.getEmail());
        oldUser.setLogin(input.getLogin());
        oldUser.setName(input.getName());
        oldUser.setBirthday(input.getBirthday());

        log.info("Обновлен пользователь: " + oldUser);

       return oldUser;
    } 
```

2024-09-06 08:47 UTC, VadimZharkov requested changes
Можно улучшить

2024-09-06 18:57 UTC, Svetlanarozanova1983 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        try {
В методе update сделала.
try...catch дорогая операция, поэтому я их использую только в фасадных методах. Действительно, сейчас источник Exception  метод валидации, далее появятся другие источники и ловушки все равно потребуются здесь.

2024-09-07 03:36 UTC, VadimZharkov approved these changes

2024-09-18 16:05 UTC, merged